export class CarsService {

    myCars = [
        {

            'id': 1,
            'cartype': 'SUV',
            'carmake': 'BMW',
            'serialnumber':'FLT32541',
            'carimage': 'assets/car1.png',
            'fuellevel': '5%',
            'distance': '200km',
            'Owner': 'SARAVANAN',
            'transmition': 'Maual',
            'serviceDue': '100days',
            'gpsid': 4587,
            'vehicleowner': 'Saravanan Govindan',
            'noofdrivers': 1,
            'chargeperhour': '$10',
            'parkinggarage': 'Velachery cross st',
            'sapid': 'SUV1589',
            'legacyid': '45879',
            'numberplate': 'USH5124',
            'fuelcost': '$50pg',
            'laborcost': '$20/hr',
            'year': 2014,
            'lastreported': 'OMR CHENNAI',
            'odometer': '150000kms',
            'oillevel': 'Green',
            'tirepressure': 'Yellow',
            'idealhours': '120hrs',
            'usedhours': '150hrs',
            'renewal': '2020'
        },
        {
            'id': 2,
            'cartype': 'Truck',
            'carmake': 'Ford',
            'carimage': 'assets/car3.png',
             'serialnumber':'FLT52541',
            'fuellevel': '10%',
            'distance': '200km',
            'Owner': 'Badri',
            'transmition': 'Auto',
            'serviceDue': '70days',
            'gpsid': 4587,
            'vehicleowner': 'SG',
            'noofdrivers': 1,
            'chargeperhour': '$15',
            'parkinggarage': 'Velachery cross st',
            'sapid': 'SUV55555',
            'legacyid': '45880',
            'numberplate': 'USH5100',
            'fuelcost': '$60pg',
            'laborcost': '$50/hr',
            'year': 2014,
            'lastreported': 'ECR CHENNAI',
            'odometer': '70000kms',
            'oillevel': 'Green',
            'tirepressure': 'Green',
            'idealhours': '110hrs',
            'usedhours': '120hrs',
            'renewal': '2025'
        },
        {
            'id': 3,
            'cartype': 'Othes',
            'carmake': 'BMW',
            'carimage': 'assets/car2.png',
             'serialnumber':'FLT32741',
            'fuellevel': '15%',
            'distance': '200km',
            'Owner': 'SARAVANAN',
            'transmition': 'Maual',
            'serviceDue': '100days',
            'gpsid': 4587,
            'vehicleowner': 'Saravanan Govindan',
            'noofdrivers': 1,
            'chargeperhour': '$10',
            'parkinggarage': 'Velachery cross st',
            'sapid': 'SUV1589',
            'legacyid': '45879',
            'numberplate': 'USH5124',
            'fuelcost': '$50pg',
            'laborcost': '$20/hr',
            'year': 2014,
            'lastreported': 'OMR CHENNAI',
            'odometer': '150000kms',
            'oillevel': 'Green',
            'tirepressure': 'Yellow',
            'idealhours': '120hrs',
            'usedhours': '150hrs',
            'renewal': '2020'
        },
        {
            'id':4,
            'cartype': 'SUV',
            'carmake': 'Mahindra',
            'carimage': 'assets/car1.png',
             'serialnumber':'FLT62541',
            'fuellevel': '20%',
            'distance': '2100km',
            'Owner': 'Govindan',
            'transmition': 'Auto',
            'serviceDue': '120days',
            'gpsid': 4587,
            'vehicleowner': 'Krishnan',
            'noofdrivers': 1,
            'chargeperhour': '$12',
            'parkinggarage': 'Main road madurai',
            'sapid': 'SUV1189',
            'legacyid': '45179',
            'numberplate': 'USH5121',
            'fuelcost': '$150pg',
            'laborcost': '$220/hr',
            'year': 2014,
            'lastreported': 'bangalore',
            'odometer': '60000kms',
            'oillevel': 'Yellow',
            'tirepressure': 'Green',
            'idealhours': '330hrs',
            'usedhours': '140hrs',
            'renewal': '2021'
        },
        {
            'id': 5,
            'cartype': 'Truck',
            'carmake': 'ford',
            'carimage': 'assets/car3.png',
             'serialnumber':'FLT72541',
            'fuellevel': '25%',
            'distance': '2000km',
            'Owner': 'Muthu',
            'transmition': 'Maual',
            'serviceDue': '100days',
            'gpsid': 4587,
            'vehicleowner': 'Rajkumar',
            'noofdrivers': 1,
            'chargeperhour': '$15',
            'parkinggarage': 'London town',
            'sapid': 'SUV1589',
            'legacyid': '45879',
            'numberplate': 'USH5104',
            'fuelcost': '$150pg',
            'laborcost': '$120/hr',
            'year': 2011,
            'lastreported': 'london',
            'odometer': '160000kms',
            'oillevel': 'red',
            'tirepressure': 'Yellow',
            'idealhours': '120hrs',
            'usedhours': '150hrs',
            'renewal': '2024'
        }        
    ]

    getCars() {
        return this.myCars;
    }

    getCar(id) {
        return this.myCars.find(car => car.id == id);
    }
}